force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>App-{000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Display_Description__c.field-meta.xml
<CustomField>
    <fullName>Display_Description__c</fullName>
    <label>Display Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Reference_Application__c.field-meta.xml
<CustomField>
    <fullName>Reference_Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reference Application</label>
    <referenceTo>Reference_Application__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/Application_Detail__c.object-meta.xml
<CustomObject>
    <description>Use this object to represent both original question-criteria and the applicants response &quot;Answer&quot;.</description>
    <label>Application Detail</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Application Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Detail__c/fields/Application_Section__c.field-meta.xml
<CustomField>
    <fullName>Application_Section__c</fullName>
    <label>Application Section</label>
    <referenceTo>Application_Section__c</referenceTo>
    <relationshipLabel>Application Details</relationshipLabel>
    <relationshipName>Application_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Display_Rich_Text__c.field-meta.xml
<CustomField>
    <fullName>Display_Rich_Text__c</fullName>
    <label>Display Rich Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Display_Text__c.field-meta.xml
<CustomField>
    <fullName>Display_Text__c</fullName>
    <label>Display Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/File_Rename__c.field-meta.xml
<CustomField>
    <fullName>File_Rename__c</fullName>
    <label>File Rename</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Large_Device_Size__c.field-meta.xml
<CustomField>
    <fullName>Large_Device_Size__c</fullName>
    <label>Large Device Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values__c</fullName>
    <label>Picklist Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Reference_Application_Detail__c.field-meta.xml
<CustomField>
    <fullName>Reference_Application_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Application Detail</label>
    <referenceTo>Reference_Application_Detail__c</referenceTo>
    <relationshipLabel>Application Details</relationshipLabel>
    <relationshipName>Application_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Section__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Sections</relationshipLabel>
    <relationshipName>Application_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application_Section__c/fields/Reference_Application_Section__c.field-meta.xml
<CustomField>
    <fullName>Reference_Application_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Application Section</label>
    <referenceTo>Reference_Application_Section__c</referenceTo>
    <relationshipLabel>Application Sections</relationshipLabel>
    <relationshipName>Application_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/Reference_Application_Detail__c.object-meta.xml
<CustomObject>
    <label>Reference Application Detail</label>
    <nameField>
        <displayFormat>RAD-{00000000}</displayFormat>
        <label>Reference Application Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Application Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_Application_Detail__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <label>Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <label>Field Label</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/fields/File_Rename__c.field-meta.xml
<CustomField>
    <fullName>File_Rename__c</fullName>
    <inlineHelpText>The name that will be set as the file that was uploaded</inlineHelpText>
    <label>File Rename</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/fields/Large_Device_Size__c.field-meta.xml
<CustomField>
    <fullName>Large_Device_Size__c</fullName>
    <defaultValue>IF($RecordType.DeveloperName = &apos;Display_Text&apos;, &apos;12&apos;,
 IF($RecordType.DeveloperName = &apos;Display_Rich_Text&apos;, &apos;12&apos;,
 IF($RecordType.DeveloperName = &apos;Input_Text_Area_Long&apos;, &apos;12&apos;,
 &apos;6&apos;
)))</defaultValue>
    <label>Large Device Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/fields/Medium_Device_Size__c.field-meta.xml
<CustomField>
    <fullName>Medium_Device_Size__c</fullName>
    <defaultValue>IF($RecordType.DeveloperName == &apos;Display_Text&apos;, &apos;12&apos;,
 IF($RecordType.DeveloperName == &apos;Display_Rich_Text&apos;, &apos;12&apos;,
 IF($RecordType.DeveloperName == &apos;Input_Text_Area_Long&apos;, &apos;12&apos;,
 &apos;6&apos;
)))</defaultValue>
    <label>Medium Device Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/fields/Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values__c</fullName>
    <inlineHelpText>Semicolon separated list of values (EX. &apos;Yes; No; Maybe&apos;)</inlineHelpText>
    <label>Picklist Values</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/fields/Reference_Application_Section__c.field-meta.xml
<CustomField>
    <fullName>Reference_Application_Section__c</fullName>
    <label>Reference Application Section</label>
    <referenceTo>Reference_Application_Section__c</referenceTo>
    <relationshipLabel>Reference Application Details</relationshipLabel>
    <relationshipName>Reference_Application_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/fields/Small_Device_Size__c.field-meta.xml
<CustomField>
    <fullName>Small_Device_Size__c</fullName>
    <defaultValue>IF($RecordType.DeveloperName == &apos;Display_Text&apos;, &apos;12&apos;,
 IF($RecordType.DeveloperName == &apos;Display_Rich_Text&apos;, &apos;12&apos;,
 IF($RecordType.DeveloperName == &apos;Input_Text_Area_Long&apos;, &apos;12&apos;,
 &apos;6&apos;
)))</defaultValue>
    <label>Small Device Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_Application_Section__c/Reference_Application_Section__c.object-meta.xml
<CustomObject>
    <label>Reference Application Section</label>
    <nameField>
        <label>Reference Application Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reference Application Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_Application_Section__c/fields/Reference_Application__c.field-meta.xml
<CustomField>
    <fullName>Reference_Application__c</fullName>
    <label>Reference Application</label>
    <referenceTo>Reference_Application__c</referenceTo>
    <relationshipLabel>Reference Application Sections</relationshipLabel>
    <relationshipName>Reference_Application_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ApplicationTriggerHelper.cls
public with sharing class ApplicationTriggerHelper {
	public static void beforeInsert(List<Application__c> applications) {
		setApplicationDefaults(applications);
	}

	public static void afterInsert(List<Application__c> applications) {
		Set<Id> referenceApplicationIds = new Set<Id>();
		for (Application__c application : applications) {
			referenceApplicationIds.add(application.Reference_Application__c);
		}

		//Reference_Application__c.Id, Reference_Application__c
		Map<Id, Reference_Application__c> referenceApplicationMap = new Map<Id, Reference_Application__c>();
		for (Reference_Application__c referenceApplication : [
			SELECT Id, Name, Display_Description__c, Display_Name__c
			FROM Reference_Application__c
			WHERE Id = :referenceApplicationIds
		]) {
			referenceApplicationMap.put(
				referenceApplication.Id,
				referenceApplication
			);
		}

		// system.debug('referenceApplicationMap');
		// system.debug(referenceApplicationMap);

		//Reference_Applicaiton__c.Id, Reference_Application_Section__c
		Map<Id, List<Reference_Application_Section__c>> referenceApplicationSectionMap = new Map<Id, List<Reference_Application_Section__c>>();
		Set<Id> referenceApplicationSectionIds = new Set<Id>();

		for (Reference_Application_Section__c section : [
			SELECT
				Id,
				Name,
				Reference_Application__c,
				Display_Section_Name__c,
				Sort_Order__c
			FROM Reference_Application_Section__c
			WHERE Reference_Application__c = :referenceApplicationMap.keySet()
		]) {
			if (
				referenceApplicationSectionMap.containsKey(
					section.Reference_Application__c
				)
			) {
				referenceApplicationSectionMap.get(section.Reference_Application__c)
					.add(section);
			} else {
				referenceApplicationSectionMap.put(
					section.Reference_Application__c,
					new List<Reference_Application_Section__c>{ section }
				);
			}
			referenceApplicationSectionIds.add(section.Id);
		}

		// system.debug('referenceApplicationSectionMap');
		// system.debug(referenceApplicationSectionMap);

		//Reference_Application_Section__c.Id, Reference_Application_Detail__c
		Map<Id, List<Reference_Application_Detail__c>> referenceApplicationDetailMap = new Map<Id, List<Reference_Application_Detail__c>>();
		Set<Id> referenceApplicationDetailIds = new Set<Id>();

		for (Reference_Application_Detail__c detail : [
			SELECT
				Id,
				Name,
				RecordTypeId,
				RecordType.DeveloperName,
				Reference_Application_Section__c,
				Field_Label__c,
				Picklist_Values__c,
				Display_Text__c,
				Display_Rich_Text__c,
				Large_Device_Size__c,
				Medium_Device_Size__c,
				Small_Device_Size__c,
				Required__c,
				Sort_Order__c,
				Component_Name__c,
				File_Rename__c,
				Accepted_File_Types__c,
				Custom_Component_JSON__c
			FROM Reference_Application_Detail__c
			WHERE Reference_Application_Section__c = :referenceApplicationSectionIds
		]) {
			if (
				referenceApplicationDetailMap.containsKey(
					detail.Reference_Application_Section__c
				)
			) {
				referenceApplicationDetailMap.get(
						detail.Reference_Application_Section__c
					)
					.add(detail);
			} else {
				referenceApplicationDetailMap.put(
					detail.Reference_Application_Section__c,
					new List<Reference_Application_Detail__c>{ detail }
				);
			}
			referenceApplicationDetailIds.add(detail.Id);
		}

		// system.debug('referenceApplicationDetailMap');
		// system.debug(referenceApplicationDetailMap);

		//create Application_Section__c's
		List<Application_Section__c> applicationSections = new List<Application_Section__c>();
		List<Application_Detail__c> applicationDetails = new List<Application_Detail__c>();

		for (Application__c application : applications) {
			Reference_Application__c referenceApplication = referenceApplicationMap.get(
				application.Reference_Application__c
			);

			List<Reference_Application_Section__c> referenceApplicationSections = referenceApplicationSectionMap.get(
				referenceApplication.Id
			);

			for (
				Reference_Application_Section__c referenceApplicationSection : referenceApplicationSections
			) {
				Application_Section__c applicationSection = new Application_Section__c();
				applicationSection.Application__c = application.Id;
				applicationSection.Reference_Application_Section__c = referenceApplicationSection.Id;
				applicationSection.Display_Section_Label__c = referenceApplicationSection.Display_Section_Name__c;
				applicationSection.Sort_Order__c = referenceApplicationSection.Sort_Order__c;
				applicationSections.add(applicationSection);
			}
		}

		insert applicationSections;

		for (Application_Section__c applicationSection : applicationSections) {
			List<Reference_Application_Detail__c> referenceApplicationDetails = referenceApplicationDetailMap.get(
				applicationSection.Reference_Application_Section__c
			);

			if (referenceApplicationDetails == null) {
				continue;
			}

			for (
				Reference_Application_Detail__c referenceApplicationDetail : referenceApplicationDetails
			) {
				Application_Detail__c applicationDetail = new Application_Detail__c();
				applicationDetail.Application_Section__c = applicationSection.Id;
				applicationDetail.Reference_Application_Detail__c = referenceApplicationDetail.Id;
				applicationDetail.Display_Text__c = referenceApplicationDetail.Display_Text__c;
				applicationDetail.Display_Rich_Text__c = referenceApplicationDetail.Display_Rich_Text__c;
				applicationDetail.Large_Device_Size__c = referenceApplicationDetail.Large_Device_Size__c;
				applicationDetail.Medium_Device_Size__c = referenceApplicationDetail.Medium_Device_Size__c;
				applicationDetail.Small_Device_Size__c = referenceApplicationDetail.Small_Device_Size__c;
				applicationDetail.Field_Label__c = referenceApplicationDetail.Field_Label__c;
				applicationDetail.Picklist_Values__c = referenceApplicationDetail.Picklist_Values__c;
				applicationDetail.Required__c = referenceApplicationDetail.Required__c;
				applicationDetail.Sort_Order__c = referenceApplicationDetail.Sort_Order__c;
				applicationDetail.Component_Name__c = referenceApplicationDetail.Component_Name__c;
				applicationDetail.File_Rename__c = referenceApplicationDetail.File_Rename__c;
				applicationDetail.Accepted_File_Types__c = referenceApplicationDetail.Accepted_File_Types__c;
				applicationDetail.Custom_Component_JSON__c = referenceApplicationDetail.Custom_Component_JSON__c;

				// system.debug('record type name');
				// system.debug(referenceApplicationDetail.RecordType.DeveloperName);

				applicationDetail.RecordTypeId = Schema.SObjectType.Application_Detail__c.getRecordTypeInfosByDeveloperName()
					.get(referenceApplicationDetail.RecordType.DeveloperName)
					.getRecordTypeId();

				applicationDetails.add(applicationDetail);
			}
		}

		insert applicationDetails;
	}

	private static void setApplicationDefaults(
		List<Application__c> applications
	) {
		Set<Id> referenceApplicationIds = new Set<Id>();
		for (Application__c application : applications) {
			referenceApplicationIds.add(application.Reference_Application__c);
		}

		//Reference_Application__c.Id, Reference_Application__c
		Map<Id, Reference_Application__c> referenceApplicationMap = new Map<Id, Reference_Application__c>();
		for (Reference_Application__c referenceApplication : [
			SELECT Id, Name, Display_Description__c, Display_Name__c
			FROM Reference_Application__c
			WHERE Id = :referenceApplicationIds
		]) {
			referenceApplicationMap.put(
				referenceApplication.Id,
				referenceApplication
			);
		}

		system.debug('referenceApplicationMap');
		system.debug(referenceApplicationMap);

		for (Application__c application : applications) {
			Reference_Application__c referenceApplication = referenceApplicationMap.get(
				application.Reference_Application__c
			);

			application.Application_Display_Name__c = referenceApplication.Display_Name__c;
			application.Display_Description__c = referenceApplication.Display_Description__c;
		}
	}
}