force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>App-{000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Detail__c/Application_Detail__c.object-meta.xml
<CustomObject>
    <description>Use this object to represent both original question-criteria and the applicants response &quot;Answer&quot;.</description>
    <label>Application Detail</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Application Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Detail__c/fields/Application_Section__c.field-meta.xml
<CustomField>
    <fullName>Application_Section__c</fullName>
    <label>Application Section</label>
    <referenceTo>Application_Section__c</referenceTo>
    <relationshipLabel>Application Details</relationshipLabel>
    <relationshipName>Application_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/City_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Target_Field_API_Name__c</fullName>
    <formula>Reference_Application_Detail__r.City_Target_Field_API_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City Target Field API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Country_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Target_Field_API_Name__c</fullName>
    <formula>Reference_Application_Detail__r.Country_Target_Field_API_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Target Field API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_City__c.field-meta.xml
<CustomField>
    <fullName>Input_City__c</fullName>
    <label>Input City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_Country__c.field-meta.xml
<CustomField>
    <fullName>Input_Country__c</fullName>
    <label>Input Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_Currency__c.field-meta.xml
<CustomField>
    <fullName>Input_Currency__c</fullName>
    <label>Input Currency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_Date__c.field-meta.xml
<CustomField>
    <fullName>Input_Date__c</fullName>
    <label>Input Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_Number__c.field-meta.xml
<CustomField>
    <fullName>Input_Number__c</fullName>
    <label>Input Number</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Input_Postal_Code__c</fullName>
    <label>Input Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Input_State_Province__c</fullName>
    <label>Input State / Province</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_Street__c.field-meta.xml
<CustomField>
    <fullName>Input_Street__c</fullName>
    <label>Input Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_Text__c.field-meta.xml
<CustomField>
    <fullName>Input_Text__c</fullName>
    <label>Input Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Postal_Code_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code_Target_Field_API_Name__c</fullName>
    <formula>Reference_Application_Detail__r.Postal_Code_Target_Field_Api_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Postal Code Target Field API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Province_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Province_Target_Field_API_Name__c</fullName>
    <formula>Reference_Application_Detail__r.Province_Target_Field_API_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Province Target Field API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Street_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Target_Field_API_Name__c</fullName>
    <formula>Reference_Application_Detail__r.Street_Target_Field_API_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Street Target Field API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_API_Name__c</fullName>
    <formula>Reference_Application_Detail__r.Target_Field_API_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Field API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/recordTypes/Input_Address.recordType-meta.xml
<RecordType>
    <fullName>Input_Address</fullName>
    <active>true</active>
    <label>Input Address</label>
</RecordType>

force-app/main/default/objects/Application_Detail__c/recordTypes/Input_Checkbox.recordType-meta.xml
<RecordType>
    <fullName>Input_Checkbox</fullName>
    <active>true</active>
    <label>Input Checkbox</label>
</RecordType>

force-app/main/default/objects/Application_Detail__c/recordTypes/Input_Currency.recordType-meta.xml
<RecordType>
    <fullName>Input_Currency</fullName>
    <active>true</active>
    <label>Input Currency</label>
</RecordType>

force-app/main/default/objects/Application_Detail__c/recordTypes/Input_Date_Time.recordType-meta.xml
<RecordType>
    <fullName>Input_Date_Time</fullName>
    <active>true</active>
    <label>Input Date Time</label>
</RecordType>

force-app/main/default/objects/Application_Detail__c/recordTypes/Input_Email.recordType-meta.xml
<RecordType>
    <fullName>Input_Email</fullName>
    <active>true</active>
    <label>Input Email</label>
</RecordType>

force-app/main/default/objects/Application_Detail__c/recordTypes/Input_Number.recordType-meta.xml
<RecordType>
    <fullName>Input_Number</fullName>
    <active>true</active>
    <label>Input Number</label>
</RecordType>

force-app/main/default/objects/Application_Detail__c/recordTypes/Input_Picklist.recordType-meta.xml
<RecordType>
    <fullName>Input_Picklist</fullName>
    <active>true</active>
    <label>Input Picklist</label>
</RecordType>

force-app/main/default/objects/Application_Detail__c/recordTypes/Input_Text_Area_Long.recordType-meta.xml
<RecordType>
    <fullName>Input_Text_Area_Long</fullName>
    <active>true</active>
    <label>Input Text Area Long</label>
</RecordType>

force-app/main/default/objects/Application_Section__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Sections</relationshipLabel>
    <relationshipName>Application_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ApplicationDetailFlattener.cls
public without sharing class ApplicationDetailFlattener {

    @InvocableMethod(
        label='Application Detail Flattener'
        description='Takes Application Details and writes the inputted value to fields on a specified record'
    )
    public static void SetFields(List<Request> input) {

        Map<String, String> recordTypeInputFieldMap = new Map<String, String>{
            'Input_Checkbox' => 'Input_Checkbox__c',
            'Input_Checkbox_Group' => 'Input_Text__c',
            'Input_Currency' => 'Input_Currency__c',
            'Input_Date' => 'Input_Date__c',
            'Input_Date_Time' => 'Input_Datetime__c',
            'Input_Number' => 'Input_Number__c',
            'Input_Picklist' => 'Input_Text__c',
            'Input_Radio_Group' => 'Input_Text__c',
            'Input_Text' => 'Input_Text__c',
            'Input_Email' => 'Input_Text__c',
            'Input_Lookup' => 'Input_Text__c',
            'Input_Text_Area_Long' => 'Input_Text_Long__c',
            'Input_Address' => 'Input_Address'
        };

        Request request = input[0];

        List<Application_Detail__c> appDetails = [
            SELECT Id, 
                Application_Section__r.Application__c, 
                Target_Field_API_Name__c, 
                RecordType.DeveloperName, 
                Input_Checkbox__c, 
                Input_Currency__c, 
                Input_Date__c, 
                Input_Datetime__c, 
                Input_Number__c, 
                Input_Text__c, 
                Input_Text_Long__c,
                Input_Street__c,
                Input_City__c,
                Input_State_Province__c,
                Input_Postal_Code__c,
                Input_Country__c,
                Street_Target_Field_API_Name__c,
                City_Target_Field_API_Name__c,
                Province_Target_Field_API_Name__c,
                Postal_Code_Target_Field_API_Name__c,
                Country_Target_Field_API_Name__c
            FROM Application_Detail__c 
            WHERE Application_Section__r.Application__c = : request.applicationId
                AND (Target_Field_API_Name__c != null 
                OR Street_Target_Field_API_Name__c != null OR
                City_Target_Field_API_Name__c != null OR
                Province_Target_Field_API_Name__c != null OR
                Postal_Code_Target_Field_API_Name__c != null OR
                Country_Target_Field_API_Name__c != null)
            
        ];

        String targetObjectRecordId = request.targetObjectRecordId;

        String targetObjectAPIName  = (Id.valueOf(targetObjectRecordId)).getSObjectType()
            .getDescribe()
            .getName();

        Schema.SObjectType sObjectType = Schema.getGlobalDescribe().get(targetObjectAPIName);
        
        SObject sob = sObjectType.newSObject();
        sob.Id = targetObjectRecordId;

        system.debug('appDetails');
        system.debug(appDetails);

        for (Application_Detail__c appDetail : appDetails) {

            system.debug('appDetail.RecordType.DeveloperName');
            system.debug(appDetail.RecordType.DeveloperName);

            String sourceFieldApiName   = recordTypeInputFieldMap.get(appDetail.RecordType.DeveloperName);

            system.debug('sourceFieldApiName');
            system.debug(sourceFieldApiName);


            if (sourceFieldApiName == 'Input_Address') {
                String streetTargetFieldApiName         = appDetail.Street_Target_Field_API_Name__c;
                String cityTargetFieldApiName           = appDetail.City_Target_Field_API_Name__c;
                String provinceTargetFieldApiName       = appDetail.Province_Target_Field_API_Name__c	;
                String postalCodeTargetFieldApiName     = appDetail.Postal_Code_Target_Field_API_Name__c;
                String countryTargetFieldApiName        = appDetail.Country_Target_Field_API_Name__c	;

                if (streetTargetFieldApiName != null) {
                    sob.put(streetTargetFieldApiName, appDetail.Input_Street__c);
                }
                if (cityTargetFieldApiName != null) {
                    sob.put(cityTargetFieldApiName, appDetail.Input_City__c);
                }
                if (provinceTargetFieldApiName != null) {
                    sob.put(provinceTargetFieldApiName, appDetail.Input_State_Province__c);
                }
                if (postalCodeTargetFieldApiName != null) {
                    sob.put(postalCodeTargetFieldApiName, appDetail.Input_Postal_Code__c);
                }
                if (countryTargetFieldApiName != null) {
                    sob.put(countryTargetFieldApiName, appDetail.Input_Country__c);
                }

            } else if (sourceFieldApiName != null) {
                String targetFieldApiName   = appDetail.Target_Field_API_Name__c;
                Object sourceFieldValue     = appDetail.get(sourceFieldApiName);
                
                if (sourceFieldValue != null) {
                    sob.put(targetFieldApiName, sourceFieldValue);
                }
            }

            system.debug('sob');
            system.debug(sob);
        }

        update sob;
    }

    public class Request {
        @InvocableVariable(label='Application Id' required=true)
        public String applicationId;

        @InvocableVariable(label='Target Object Record Id' required=true)
        public Id targetObjectRecordId;
    }
}
/* 
ApplicationDetailFlattener.Request req = new ApplicationDetailFlattener.Request();
List<ApplicationDetailFlattener.Request> reqList = new List<ApplicationDetailFlattener.Request>();

req.applicationId = 'a05DE00000L1ulzYAB';
req.targetObjectRecordId = '001DE000039YX2SYAW';

reqList.add(req);
ApplicationDetailFlattener.setFields(reqList);
*/