force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>App-{000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Display_Description__c.field-meta.xml
<CustomField>
    <fullName>Display_Description__c</fullName>
    <label>Display Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Reference_Application__c.field-meta.xml
<CustomField>
    <fullName>Reference_Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reference Application</label>
    <referenceTo>Reference_Application__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/Application_Detail__c.object-meta.xml
<CustomObject>
    <description>Use this object to represent both original question-criteria and the applicants response &quot;Answer&quot;.</description>
    <label>Application Detail</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Application Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Detail__c/fields/City_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Target_Field_API_Name__c</fullName>
    <formula>Reference_Application_Detail__r.City_Target_Field_API_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City Target Field API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Country_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Target_Field_API_Name__c</fullName>
    <formula>Reference_Application_Detail__r.Country_Target_Field_API_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Target Field API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_City__c.field-meta.xml
<CustomField>
    <fullName>Input_City__c</fullName>
    <label>Input City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_Country__c.field-meta.xml
<CustomField>
    <fullName>Input_Country__c</fullName>
    <label>Input Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Input_Postal_Code__c</fullName>
    <label>Input Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Input_State_Province__c</fullName>
    <label>Input State / Province</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_Street__c.field-meta.xml
<CustomField>
    <fullName>Input_Street__c</fullName>
    <label>Input Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Input_Text__c.field-meta.xml
<CustomField>
    <fullName>Input_Text__c</fullName>
    <label>Input Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Postal_Code_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code_Target_Field_API_Name__c</fullName>
    <formula>Reference_Application_Detail__r.Postal_Code_Target_Field_Api_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Postal Code Target Field API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Province_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Province_Target_Field_API_Name__c</fullName>
    <formula>Reference_Application_Detail__r.Province_Target_Field_API_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Province Target Field API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Reference_Application_Detail__c.field-meta.xml
<CustomField>
    <fullName>Reference_Application_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Application Detail</label>
    <referenceTo>Reference_Application_Detail__c</referenceTo>
    <relationshipLabel>Application Details</relationshipLabel>
    <relationshipName>Application_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Street_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Target_Field_API_Name__c</fullName>
    <formula>Reference_Application_Detail__r.Street_Target_Field_API_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Street Target Field API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/fields/Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_API_Name__c</fullName>
    <formula>Reference_Application_Detail__r.Target_Field_API_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Field API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Detail__c/recordTypes/Input_Address.recordType-meta.xml
<RecordType>
    <fullName>Input_Address</fullName>
    <active>true</active>
    <label>Input Address</label>
</RecordType>

force-app/main/default/objects/Reference_Application__c/Reference_Application__c.object-meta.xml
<CustomObject>
    <label>Reference Application</label>
    <nameField>
        <label>Reference Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reference Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_Application_Detail__c/Reference_Application_Detail__c.object-meta.xml
<CustomObject>
    <label>Reference Application Detail</label>
    <nameField>
        <displayFormat>RAD-{00000000}</displayFormat>
        <label>Reference Application Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Application Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_Application_Detail__c/fields/City_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Target_Field_API_Name__c</fullName>
    <label>City Target Field API Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/fields/Country_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Target_Field_API_Name__c</fullName>
    <label>Country Target Field API Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <label>Field Label</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/fields/Postal_Code_Target_Field_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code_Target_Field_Api_Name__c</fullName>
    <label>Postal Code Target Field Api Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/fields/Province_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Province_Target_Field_API_Name__c</fullName>
    <label>Province Target Field API Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/fields/Reference_Application_Section__c.field-meta.xml
<CustomField>
    <fullName>Reference_Application_Section__c</fullName>
    <label>Reference Application Section</label>
    <referenceTo>Reference_Application_Section__c</referenceTo>
    <relationshipLabel>Reference Application Details</relationshipLabel>
    <relationshipName>Reference_Application_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/fields/Street_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Target_Field_API_Name__c</fullName>
    <label>Street Target Field API Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/fields/Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_API_Name__c</fullName>
    <label>Target Field API Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Application_Detail__c/recordTypes/Input_Text.recordType-meta.xml
<RecordType>
    <fullName>Input_Text</fullName>
    <active>true</active>
    <label>Input Text</label>
</RecordType>

force-app/main/default/objects/Reference_Application_Section__c/Reference_Application_Section__c.object-meta.xml
<CustomObject>
    <label>Reference Application Section</label>
    <nameField>
        <label>Reference Application Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reference Application Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_Application_Section__c/fields/Reference_Application__c.field-meta.xml
<CustomField>
    <fullName>Reference_Application__c</fullName>
    <label>Reference Application</label>
    <referenceTo>Reference_Application__c</referenceTo>
    <relationshipLabel>Reference Application Sections</relationshipLabel>
    <relationshipName>Reference_Application_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ApplicationDetailFlattenerTest.cls
@isTest
public with sharing class ApplicationDetailFlattenerTest {
 
    @TestSetup
    static void makeData() {

        Reference_Application__c refApp = new Reference_Application__c();
        refApp.Name = 'test';
        refApp.Display_Description__c = 'testDisplayDescription';
        refApp.Display_Name__c = 'testDisplayName';
        insert refApp;

        Reference_Application_Section__c refAppSection = new Reference_Application_Section__c();
        refAppSection.Name = 'testName';
        refAppSection.Reference_Application__c = refApp.Id;
        refAppSection.Display_Section_Name__c = 'testDisplaySectionName';
        refAppSection.Sort_Order__c = 1;
        insert refAppSection;

        Reference_Application_Detail__c refAppDetail = new Reference_Application_Detail__c();  
        refAppDetail.Field_Label__c = 'test text input';
        refAppDetail.Target_Field_API_Name__c = 'Input_Text__c';
        refAppDetail.Reference_Application_Section__c = refAppSection.Id;
        refAppDetail.RecordTypeId = Schema.SObjectType.Reference_Application_Detail__c.getRecordTypeInfosByDeveloperName()
            .get('Input_Text')
            .getRecordTypeId();
        refAppDetail.Sort_Order__c = 1;
        insert refAppDetail;

        Reference_Application_Detail__c refAppDetailAddress = new Reference_Application_Detail__c();  
        refAppDetailAddress.Field_Label__c = 'Address';
        // refAppDetail.Target_Field_API_Name__c = 'Input_Text__c';
        refAppDetailAddress.Street_Target_Field_API_Name__c = 'Input_Street__c';
        refAppDetailAddress.City_Target_Field_API_Name__c = 'Input_City__c';
        refAppDetailAddress.Province_Target_Field_API_Name__c = 'Input_State_Province__c';
        refAppDetailAddress.Postal_Code_Target_Field_API_Name__c = 'Input_Postal_Code__c';
        refAppDetailAddress.Country_Target_Field_API_Name__c = 'Input_Country__c';

        refAppDetailAddress.Reference_Application_Section__c = refAppSection.Id;
        refAppDetailAddress.RecordTypeId = Schema.SObjectType.Reference_Application_Detail__c.getRecordTypeInfosByDeveloperName()
            .get('Input_Address')
            .getRecordTypeId();
            refAppDetailAddress.Sort_Order__c = 2;
        insert refAppDetailAddress;
    }

    @isTest
    private static void SetFieldsTest() {

        Reference_Application__c refApp = [SELECT Id FROM Reference_Application__c LIMIT 1];

        Application__c app = new Application__c();
        app.Reference_Application__c = refApp.Id;
        insert app;

        List<Application_Detail__c> details = [SELECT Id, RecordType.DeveloperName FROM Application_Detail__c];

        for (Application_Detail__c detail : details) {
            if (detail.RecordType.DeveloperName == 'Input_Text') {
                detail.Input_Text__c = 'ayy yoo';
            }
            if (detail.RecordType.DeveloperName == 'Input_Address') {
                detail.Input_Street__c = 'test';
                detail.Input_City__c = 'test';
                detail.Input_State_Province__c = 'test';
                detail.Input_Postal_Code__c = 'test';
                detail.Input_Country__c = 'test';            
            }
        }
        
        update details;

        ApplicationDetailFlattener.Request req = new ApplicationDetailFlattener.Request();
            req.applicationId = app.Id;
            req.targetObjectRecordId = details[0].Id;
        
        ApplicationDetailFlattener.SetFields(new List<ApplicationDetailFlattener.Request>{ req });

        System.assertEquals(details[0].Input_Text__c, 'ayy yoo');
    }

}